# $ make
default:
	echo 'Hello World'

echo_without_output_running_command:
	@echo 'Hello World'

ary_loop:
	@for i in 1 2 3; do\
		echo $$i;\
	done

ls_loop:
	@for i in `ls ..`; do\
		echo $$i;\
	done
